### ISSUE TITLE
How to customize node-resque connection options

### ISSUE THREAD

**Issue by dubiousdavid** [actionhero/ah-resque-ui#212]
I need to customize `namespace` and use Redis sentinel with `ioredis`. How can I accomplish this?

**Comment by evantahler** [comment]
Hello! Are you asking about how to do this for this package, `node-resque` in general, or in `actionhero`?

You can pass the `namespace` option to node-resque per https://github.com/actionhero/node-resque#configuration-options.  In Actionhero, which this plugin users, it would be set in `config.tasks.connectionOptions.namespace`

**Comment by dubiousdavid** [comment]
Thanks. That was what I was looking for. In case anyone else reads this in the future, the correct config path is: `config.tasks.connectionOptions.tasks.namespace`.
