### ISSUE TITLE
docs are out of date or not working

### ISSUE THREAD

**Issue by liesislukas** [actionhero/ah-resque-ui#55]
Hi, trying to launch your software. It has error "unknown action or invalid apiVersion.

```
mkdir resque
cd resque/
npm init
npm i actionhero --save
node ./node_modules/.bin/actionhero generate
npm i
npm i ah-resque-ui --save
node ./node_modules/.bin/actionhero link --name ah-resque-ui
node ./node_modules/.bin/actionhero start
```

```
actionhero@17.0.0
node -v v7.8.0
npm -v 4.2.0
```

![image](https://cloud.githubusercontent.com/assets/2733862/25784016/df9b4d70-336e-11e7-8912-bbcc57ebf514.png)

![image](https://cloud.githubusercontent.com/assets/2733862/25784025/187e3b84-336f-11e7-807d-f469305b57a6.png)

will try to use actionhero version 13.x now

**Comment by evantahler** [comment]
Thank you for this!
You found a bug in actionhero actually, which has now been fixed

**Comment by liesislukas** [comment]
thanks for quick fix 👍  Also would be great to have clear step-by-step how to start it up in production, while i had to dig the code to find out that you use ENV variables to set connection to redis info.

**Comment by liesislukas** [comment]
I'm running and it works well now 👍 

```
    "actionhero": "^17.0.1",
    "ah-resque-ui": "^0.3.0"
````
