### ISSUE TITLE
some ideas for better usability while using UI

### ISSUE THREAD

**Issue by liesislukas** [actionhero/ah-resque-ui#56]
First of all, thank you for this UI. It helps to see what's happening. Below are some ideas what would help to see "action" even better:

![image](https://cloud.githubusercontent.com/assets/2733862/25848859/e5bbf0ae-34c4-11e7-85cb-6d28531e86af.png)

**Comment by liesislukas** [comment]
Could you add some info inside readme how do you test while developing?

**Comment by evantahler** [comment]
Notes added to the readme https://github.com/actionhero/ah-resque-ui/blob/master/README.md#testing--developing

**Comment by evantahler** [comment]
A
