### ISSUE TITLE
ah-resque-ui "ah is not defined"

### ISSUE THREAD

**Issue by ferpalma21** [actionhero/ah-resque-ui#61]
I was setting up ah-resque-ui and followed the instructions from step 1-3, [instructions](https://github.com/actionhero/ah-resque-ui) , but when I run action hero throws the next error 'ah is not defined'

my files:

config/plugins.js
```
exports['default'] = {
  plugins: (api) => {
    return {
       'ah-resque-ui': { path: __dirname + '/../node_modules/ah-resque-ui' }
    }
  }
}

```
config/ah-resque-ui.js

`ah`

thanks in advance :)

**Comment by evantahler** [comment]
Sorry about that!  We lost a chunk of the readme. https://github.com/actionhero/ah-resque-ui/commit/da293f70c2ac666018006f71ce953ad61656442c

**Comment by ferpalma21** [comment]
thank you very much evan :)
