### ISSUE TITLE
Paged list of failed tasks not working correctly

### ISSUE THREAD

**Issue by bayssmekanique** [actionhero/ah-resque-ui#62]
When clicking the `Retry` or `Remove` buttons on a paginated list of failed tasks, it appears to be missing the pagination offset or something, because it is not performing the action on the targetted task.

![capture1](https://user-images.githubusercontent.com/2280384/43106134-3ace7554-8e8c-11e8-966b-6cd4218108e5.png)

In this first image, I clicked `Retry` on number `99`, `task:mSeriesAppImport:882b1d88-...`.

![capture2](https://user-images.githubusercontent.com/2280384/43106138-3d320b62-8e8c-11e8-8440-6bbe09540b7e.png)

Rather than disappearing, it moves up the list to spot number `98`, and I'm assuming the task in spot `49` on the first page was just retried.

**Comment by evantahler** [comment]
fixed in https://github.com/actionhero/ah-resque-ui/commit/1ba8fc6a1f59e4fbee6c9924ad345229b7453f84

**Comment by evantahler** [comment]
good luck!
