### ISSUE TITLE
All hrefs should be /public/...

### ISSUE THREAD

**Issue by evantahler** [actionhero/ah-resque-ui#70]
Like this https://github.com/actionhero/ah-resque-ui/blob/master/public/resque/index.html#L11 and the images

**Comment by evantahler** [comment]
cc @bleonard

**Comment by evantahler** [comment]
solved by 2d2bb4c

**Comment by bleonard** [comment]
looks like the icon path needs updating in css: http://localhost:3001/resque/img/resque-logo.png

**Comment by evantahler** [comment]
fixed in https://github.com/actionhero/ah-resque-ui/commit/44584716b849d0eb55cbce1e8afef966f7979b82
